### ISSUE TITLE
Can't add listview inside PlatformAlertDialog

### ISSUE THREAD

**Issue by mancj** [stryder-dev/flutter_platform_widgets#229]
Hello! Thank you for this amazing library!

I have the following code, which works fine:
```dart
@override
  Widget build(BuildContext context) {
    return BlocProvider<CollectionsPickerCubit>(
      create: (context) => _cubit,
      child: PlatformAlertDialog(
        title: Text(S.of(context).selectCollections),
        material: (_, __) => MaterialAlertDialogData(
          contentPadding: EdgeInsets.only(top: 16, left: 24, right: 24, bottom: 0),
        ),
        content: Container(
          child: BlocBuilder<CollectionsPickerCubit, CollectionsState>(
            builder: (context, state) => Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Scrollbar(
                  thickness: 2,
                  child: ConstrainedBox(
                    constraints: BoxConstraints(maxHeight: 230),
                    child: ListView(
                      shrinkWrap: true,
                      children: _collectionsList(context, state),
                    ),
                  ),
                ),
                ..._additionalButtons(context),
              ],
            ),
          ),
        ),
        actions: [
          PlatformDialogAction(
              child: Text(S.of(context).cancel),
              onPressed: () {
                Navigator.pop(context);
              }),
          PlatformDialogAction(
            child: Text(S.of(context).done),
            onPressed: () async {
              await _cubit.saveFavorites();
              Navigator.pop(context);
            },
          ),
        ],
      ),
    );
  }
```

But i need to remove inset padding from dialog, so when i add 
```dart
          insetPadding: EdgeInsets.all(2)
```
to `MaterialAlertDialogData` it doesn't render and i get the following error

```dart
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
RenderShrinkWrappingViewport does not support returning intrinsic dimensions.

Calculating the intrinsic dimensions would require instantiating every child of the viewport, which defeats the point of viewports being lazy.

If you are merely trying to shrink-wrap the viewport in the main axis direction, you should be able to achieve that effect by just giving the viewport loose constraints, without needing to measure its intrinsic dimensions.

The relevant error-causing widget was: 
  PlatformAlertDialog file:///Users/mancj/Super/mancj/maajim_flutter/lib/screens/collections/dialogs/collections_picker_dialog.dart:45:14
When the exception was thrown, this was the stack: 
#0      RenderShrinkWrappingViewport.debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1798:9)
#1      RenderShrinkWrappingViewport.debugThrowIfNotCheckingIntrinsics (package:flutter/src/rendering/viewport.dart:1812:6)
#2      RenderViewportBase.computeMaxIntrinsicHeight (package:flutter/src/rendering/viewport.dart:434:12)
#3      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1373:23)
#4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
...
The following RenderObject was being processed when the exception was fired: RenderIntrinsicWidth#e8d44 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(280.0<=w<=356.0, 0.0<=h<=644.0)
...  size: MISSING
...  stepWidth: null
...  stepHeight: null
RenderObject: RenderIntrinsicWidth#e8d44 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(280.0<=w<=356.0, 0.0<=h<=644.0)
  size: MISSING
  stepWidth: null
  stepHeight: null
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by aqwert** [comment]
This is how `ListView` widget works. I suggest replacing the list view with

```
SingleChildScrollView(
    child: Column(children: [...])
)
```

**Comment by mancj** [comment]
But how does `ListView` depend on `insetPadding` and why does it work fine without it?

**Comment by aqwert** [comment]
That is probably more of a question directed at flutter devs. This package only wraps the existing flutter material and cupertino widgets to create a single interface.

**Comment by erperejildo** [comment]
Facing same problem

**Comment by aqwert** [comment]
I am going to close this as the issue you are facing is down to flutter itself and how you build your dialog.
