### ISSUE TITLE
`showPlatformDialog` throws assertion error on iOS

### ISSUE THREAD

**Issue by tmaihoff** [stryder-dev/flutter_platform_widgets#374]
`showPlatformDialog` throws assertion error on iOS.

How to reproduce:
-----
1. Call `showPlatformDialog` on the iOS simulator
2. See the following assertion error

```log
flutter: 'package:flutter_platform_widgets/src/platform.dart': Failed assertion: line 190 pos 12: 'cupertino?.builder != null || cupertino != null': is not true.
package:flutter_platform_widgets/src/platform.dart:190
flutter:
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      showPlatformDialog
package:flutter_platform_widgets/src/platform.dart:190
#3      AboutDialogListTile.build.<anonymous closure>.<anonymous closure>
package:ifr_flight_simulator/…/presentation/about_dialog_list_tile.dart:30
#4      _ListTileBackgroundState._handleTap
package:cupertino_list_tile/src/list_tile_background.dart:304
#5      _ListTileBackgroundState.build.<anonymous closure>
package:cupertino_list_tile/src/list_tile_background.dart:370
#6      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:253
#7      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:627
#8      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:306
#9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.da<…>
```

Possible solution
--- 
The equivilant assertion in the material section is:
`    assert(material?.builder != null || builder != null);`
The throwing assertion in the cupertino section is:
`    assert(cupertino?.builder != null || cupertino != null);`

The latter should be 
`    assert(cupertino?.builder != null || builder != null);`

**Comment by tmaihoff** [comment]
PR opened, please review

**Comment by aqwert** [comment]
Version 2.2.5 updated with this fix
